version: '2'

services:

  nginx:
    container_name: nette-nginx
    build: ./.docker/nginx/
    ports:
    - 1080:80
    volumes:
    - ./:/code
    - ./.docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    - ./.docker/nginx/log:/var/log/nginx
    links:
    - php:php


  php:
    container_name: nette-php
    build: ./.docker/php/
    ports:
    - 1009:9000
    volumes:
    - ./:/code
    - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
    links:
    - mysql:mysql
    - redis:redis


  mysql:
    container_name: nette-mysql
    build: ./.docker/mysql/
    ports:
    - 1306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nette
      MYSQL_USER: nette
      MYSQL_PASSWORD: nette


  memcached:
    container_name: nette-memcached
    build: ./.docker/memcached
    #image: memcached:latest
    ports:
      - 11211:11211

  redis:
    container_name: nette-redis
    build: ./.docker/redis/
    ports:
    - 1079:6379
    volumes:
    - ./.docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf


